=== dadadaniil/Java_Practice_XML_11/src/main/resources/results.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="results">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="student" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="login" type="xsd:string"/>
                            <xsd:element name="tests">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="test" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                                <xsd:attribute name="date" type="xsd:date" use="required"/>
                                                <xsd:attribute name="mark" type="xsd:float" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== dadadaniil/Java_Practice_XML_11/src/main/resources/results.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:tns="file://C:/Users/Dadadaniil/IdeaProjects/Java_Practice_XML_11/src/main/resources/results.xsd"
             xsi:noNamespaceSchemaLocation="results.xsd">
    <student>
        <login>cool</login>
        <tests>
            <test name="oop" date="2023-03-20" mark="8.5"/>
            <test name="xml" date="2023-03-23" mark="7.3"/>
            <test name="oop" date="2023-03-27" mark="9.4"/>
            <test name="jdbc" date="2023-03-27" mark="6.8"/>
            <test name="xml" date="2023-03-29" mark="7.9"/>
        </tests>
    </student>
    <student>
        <login>clever</login>
        <tests>
            <test name="oop" date="2023-03-27" mark="7.0"/>
            <test name="collections" date="2023-03-28" mark="6.4"/>
        </tests>
    </student>
</tns:results>
